name 'opsworks-linux-demo-cookbook-django'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures opsworks-linux-demo-cookbook-django'
long_description 'Installs/Configures opsworks-linux-demo-cookbook-django'
version '0.1.0'

depends 'application_python'
depends 'build-essential'
depends 'poise-python'
